MPI: MIPS: Fix compilation error with GCC 5.1
commit 9d98c1d207a9943d44a185c784792157f8b7233e
Author: Senthil Kumar Rajagopal <skrajago@codeaurora.org>
Date:   Tue Dec 1 03:40:21 2015 -0500

    [PATCH] Fix extern inline use for gcc > 4.3 in c99 mode

    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 8a9c427048b1274b2ec6c3db576426e95e39ca9a
Author: Stephan Mueller <smueller@chronox.de>
Date:   Sun Oct 18 12:45:18 2015 +0200

    lib/mpi: fix off by one in mpi_read_raw_from_sgl

    The patch fixes the analysis of the input data which contains an off
    by one.

    The issue is visible when the SGL contains one byte per SG entry.
    The code for checking for zero bytes does not operate on the data byte.

    Signed-off-by: Stephan Mueller <smueller@chronox.de>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit ec8ce9faf58032000a9c8a89d8ee761476c27d72
Author: Christoph Hellwig <hch@lst.de>
Date:   Fri Aug 28 09:27:15 2015 +0200

    move count_zeroes.h out of asm-generic

    This header contains a few helpers currenly only used by the mpi
    implementation, and not default implementation of architecture code.

    Signed-off-by: Christoph Hellwig <hch@lst.de>
    Signed-off-by: Arnd Bergmann <arnd@arndb.de>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 489ed2b051cddbd4d64869cbe12c61bf08631997
Author: Tadeusz Struk <tadeusz.struk@intel.com>
Date:   Thu Oct 8 09:26:50 2015 -0700

    lib/mpi: Add mpi sgl helpers

    Add mpi_read_raw_from_sgl and mpi_write_to_sgl helpers.

    Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 04d0146ddb577fe50f0e00153f623f4ce7fccec3
Author: Tadeusz Struk <tadeusz.struk@intel.com>
Date:   Mon Aug 24 07:52:14 2015 -0700

    MPI: Fix mpi_read_buffer

    Change mpi_read_buffer to return a number without leading zeros
    so that mpi_read_buffer and mpi_get_buffer return the same thing.

    Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 0023b8b08ce6216d4baf7efcf2178cebd257515c
Author: Tadeusz Struk <tadeusz.struk@intel.com>
Date:   Mon Jun 15 13:18:36 2015 -0700

    MPILIB: add mpi_read_buf() and mpi_get_size() helpers

    Added a mpi_read_buf() helper function to export MPI to a buf provided by
    the user, and a mpi_get_size() helper, that tells the user how big the buf is.
    Changed mpi_free to use kzfree instead of kfree because it is used to free
    crypto keys.

    Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>
    Signed-off-by: Herbert Xu <herbert@gondor.apana.org.au>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit dbe37db861c0b6e5f35a4c76f819979be51c72af
Author: Jaedon Shin <jaedon.shin@gmail.com>
Date:   Fri Jun 12 18:04:14 2015 +0900

    MPI: MIPS: Fix compilation error with GCC 5.1

    This patch fixes mips compilation error:

    lib/mpi/generic_mpih-mul1.c: In function 'mpihelp_mul_1':
    lib/mpi/longlong.h:651:2: error: impossible constraint in 'asm'

    Signed-off-by: Jaedon Shin <jaedon.shin@gmail.com>
    Cc: Linux-MIPS <linux-mips@linux-mips.org>
    Patchwork: https://patchwork.linux-mips.org/patch/10546/
    Signed-off-by: Ralf Baechle <ralf@linux-mips.org>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit a24dac98923519ad86f059805732da1ebe0aa538
Author: Rasmus Villemoes <linux@rasmusvillemoes.dk>
Date:   Wed Jan 14 16:10:12 2015 +0000

    MPILIB: Fix comparison of negative MPIs

    If u and v both represent negative integers and their limb counts
    happen to differ, mpi_cmp will always return a positive value - this
    is obviously bogus. u is smaller than v if and only if it is larger in
    absolute value.

    Signed-off-by: Rasmus Villemoes <linux@rasmusvillemoes.dk>
    Signed-off-by: David Howells <dhowells@redhat.com>
    Acked-by: Dmitry Kasatkin <dmitry.kasatkin@gmail.com>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 2ddd1b1fa256c8387c0d8a12826ccc2d14ca6bb6
Author: Rasmus Villemoes <linux@rasmusvillemoes.dk>
Date:   Wed Jan 14 15:16:00 2015 +0000

    MPILIB: Fix obvious but harmless typo

    The macro MPN_COPY_INCR this occurs in isn't used anywhere.

    Signed-off-by: Rasmus Villemoes <linux@rasmusvillemoes.dk>
    Signed-off-by: David Howells <dhowells@redhat.com>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 8fe7598baa48beec56fd9d698a202d9615634c88
Author: Rasmus Villemoes <linux@rasmusvillemoes.dk>
Date:   Wed Jan 14 15:15:57 2015 +0000

    MPILIB: Deobfuscate mpi_cmp

    The condition preceding 'return 1;' makes my head hurt. At this point,
    we know that u and v have the same sign; if they are negative, they
    compare opposite to how their absolute values compare (which
    mpihelp_cmp found for us), otherwise cmp itself is the
    answer. Negating cmp is ok since mpihelp_cmp returns {-1,0,1};
    -INT_MIN==INT_MIN won't bite us.

    Signed-off-by: Rasmus Villemoes <linux@rasmusvillemoes.dk>
    Signed-off-by: David Howells <dhowells@redhat.com>
    Acked-by: Dmitry Kasatkin <dmitry.kasatkin@gmail.com>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 7d2a4a8753ce70348ca3ee9a91f2c028eee267d5
Author: Konstantin Khlebnikov <khlebnikov@openvz.org>
Date:   Tue Sep 17 15:14:52 2013 +0400

    MPILIB: add module description and license

    This patch fixes lack of license, otherwise mpi.ko taints kernel.

    Signed-off-by: Konstantin Khlebnikov <khlebnikov@openvz.org>
    Signed-off-by: David Howells <dhowells@redhat.com>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

commit 90ffb6ddb026d2ccfc084d7fb946348e1f158f01
Author: Richard Henderson <rth@twiddle.net>
Date:   Wed Jul 10 11:05:59 2013 -0700

    alpha: Modernize lib/mpi/longlong.h

    Remove the compile warning for __udiv_qrnnd not having a prototype.
    Use the __builtin_alpha_umulh introduced in gcc 4.0.

    Reviewed-and-Tested-by: Matt Turner <mattst88@gmail.com>
    Signed-off-by: Matt Turner <mattst88@gmail.com>
    Signed-off-by: Richard Henderson <rth@twiddle.net>
    Signed-off-by: mydongistiny <jaysonedson@gmail.com>

Signed-off-by: mydongistiny <jaysonedson@gmail.com>